# Generated by Django 4.2.7 on 2026-04-29 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ModèleSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle de sondage',
                'verbose_name_plural': 'Modèles de sondage',
            },
        ),
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_prive', models.BooleanField(default=False)),
                ('mode_passe', models.CharField(blank=True, max_length=100)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('une_seule_reponse', models.BooleanField(default=True, help_text='Empêcher un même participant de répondre plusieurs fois')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondages_crees', to=settings.AUTH_USER_MODEL)),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sondages', to='surveys.modèlesondage')),
            ],
            options={
                'verbose_name': 'Sondage',
                'verbose_name_plural': 'Sondages',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('type_question', models.CharField(choices=[('choix_unique', 'Choix unique'), ('choix_multiple', 'Choix multiple'), ('echelle', 'Échelle (1-5)'), ('texte', 'Texte libre')], default='choix_unique', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('est_obligatoire', models.BooleanField(default=True)),
                ('condition_choix', models.ForeignKey(blank=True, help_text='Le choix qui doit être sélectionné pour afficher cette question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='surveys.choix')),
                ('condition_question', models.ForeignKey(blank=True, help_text="Question dont la réponse conditionne l'affichage de cette question", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_conditionnelles', to='surveys.question')),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.sondage')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='choix',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question'),
        ),
    ]
