# Generated by Django 4.2.7 on 2026-04-29 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_complete', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(help_text='Participant identifié ou anonyme ayant soumis cette réponse', on_delete=django.db.models.deletion.CASCADE, to='accounts.participant')),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.sondage')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ReponseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_texte', models.TextField(blank=True)),
                ('choix_selectionnes', models.ManyToManyField(blank=True, help_text='Choix sélectionnés (pour choix unique ou multiple)', to='surveys.choix')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responses.reponse')),
            ],
            options={
                'verbose_name': 'Détail de réponse',
                'verbose_name_plural': 'Détails de réponses',
                'unique_together': {('reponse', 'question')},
            },
        ),
    ]
